import {
  Member,
  Visitor,
  ChurchService,
  AttendanceRecord,
  HeadcountRecord,
  GivingRecord,
  PledgeRecord,
  PledgeCampaign,
  ExpenseRecord,
  Ministry,
  SmallGroup,
  ChurchEvent,
  PastoralCareRecord,
  PrayerRequest,
  CommunicationRecord,
  AuditLog,
  ChurchSettings,
  UserProfile,
} from '../types/database.types';

export const initialSettings: ChurchSettings = {
  church_name: 'Greater Works City Church',
  branch_name: 'Joma Assembly',
  short_name: 'GWCC',
  senior_pastor: 'Prophet Elisha K. Richard',
  general_secretary: 'Tamekloe Clara Gaewornu',
  logo_url: '/assets/logo.png',
  location: 'Joma, Accra, Ghana',
  address: 'Main High Street, Adjacent to Joma Market, Joma, Accra',
  gps_address: 'GA-183-4921',
  phone: '+233 24 456 7890',
  email: 'admin@greaterworkscitychurch.org',
  currency: 'GHS',
  currency_symbol: 'GH₵',
  timezone: 'Africa/Accra',
};

export const sampleUsers: UserProfile[] = [
  {
    id: 'usr-001',
    first_name: 'Prophet Elisha',
    last_name: 'K. Richard',
    email: 'kelisharichard@gmail.com',
    phone: '+233 24 111 2233',
    role: 'senior_pastor',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-01-01T08:00:00Z',
    updated_at: '2025-01-01T08:00:00Z',
  },
  {
    id: 'usr-002',
    first_name: 'Kofi',
    last_name: 'Mensah-Bonsu',
    email: 'admin@greaterworkscitychurch.org',
    phone: '+233 24 222 3344',
    role: 'super_admin',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-01-01T08:00:00Z',
    updated_at: '2025-01-01T08:00:00Z',
  },
  {
    id: 'usr-003',
    first_name: 'Akosua',
    last_name: 'Frimpong',
    email: 'finance@greaterworkscitychurch.org',
    phone: '+233 20 333 4455',
    role: 'finance_officer',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-01-05T09:00:00Z',
    updated_at: '2025-01-05T09:00:00Z',
  },
  {
    id: 'usr-004',
    first_name: 'Pastor David',
    last_name: 'Osei-Tutu',
    email: 'pastor.david@greaterworkscitychurch.org',
    phone: '+233 55 444 5566',
    role: 'pastor',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'usr-005',
    first_name: 'Ebenezer',
    last_name: 'Quaye',
    email: 'attendance@greaterworkscitychurch.org',
    phone: '+233 24 555 6677',
    role: 'attendance_officer',
    is_active: true,
    created_at: '2025-02-10T08:30:00Z',
    updated_at: '2025-02-10T08:30:00Z',
  },
  {
    id: 'usr-006',
    first_name: 'Abena',
    last_name: 'Amoako',
    email: 'data.entry@greaterworkscitychurch.org',
    phone: '+233 20 666 7788',
    role: 'data_entry',
    is_active: true,
    created_at: '2025-03-01T09:15:00Z',
    updated_at: '2025-03-01T09:15:00Z',
  },
  {
    id: 'usr-007',
    first_name: 'Clara',
    last_name: 'Tamekloe Gaewornu',
    email: 'clara.gaewornu@greaterworkscitychurch.org',
    phone: '+233 24 777 8899',
    role: 'administrator',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr-008',
    first_name: 'Sister Grace',
    last_name: 'Boateng',
    email: 'choir.leader@greaterworkscitychurch.org',
    phone: '+233 50 888 9900',
    role: 'ministry_leader',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: '2025-02-01T09:00:00Z',
    updated_at: '2025-02-01T09:00:00Z',
  },
];

export const sampleServices: ChurchService[] = [
  {
    id: 'srv-001',
    name: 'Sunday 1st Service (Prophetic Encounter)',
    type: 'sunday',
    day_of_week: 'Sunday',
    start_time: '07:30',
    end_time: '09:30',
    venue: 'Main Cathedral Sanctuary, Joma',
    service_leader: 'Pastor David Osei-Tutu',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Voice of Dominion (Choir)',
    expected_attendance: 180,
    description: 'Early morning communion, worship, and prophetic word for divine direction.',
    is_active: true,
    order_of_service: [
      { id: 'item-101', order: 1, time: '07:30 - 07:45', title: 'Opening Prayer & Faith Declarations', minister: 'Elder Kenneth Asare', duration: '15 min' },
      { id: 'item-102', order: 2, time: '07:45 - 08:15', title: 'Intense Praise & Adoration', minister: 'Voice of Dominion Choir', duration: '30 min' },
      { id: 'item-103', order: 3, time: '08:15 - 08:30', title: 'Welcome of Visitors & Announcements', minister: 'Deaconess Akosua Frimpong', duration: '15 min' },
      { id: 'item-104', order: 4, time: '08:30 - 08:45', title: 'Covenant Tithes & Offering Exhortation', minister: 'Pastor David Osei-Tutu', duration: '15 min' },
      { id: 'item-105', order: 5, time: '08:45 - 09:20', title: 'Prophetic Sermon & Impartation Ministry', minister: 'Prophet Elisha K. Richard', duration: '35 min' },
      { id: 'item-106', order: 6, time: '09:20 - 09:30', title: 'Holy Communion & Benediction', minister: 'Senior Pastoral Board', duration: '10 min' },
    ],
  },
  {
    id: 'srv-002',
    name: 'Sunday 2nd Service (Celebration Service)',
    type: 'sunday',
    day_of_week: 'Sunday',
    start_time: '10:00',
    end_time: '12:30',
    venue: 'Main Cathedral Sanctuary, Joma',
    service_leader: 'Lady Pastor Mercy Agyemang',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Minister Kwadwo Boateng',
    expected_attendance: 350,
    description: 'High praise, congregational celebration worship, child dedication, and apostolic doctrine.',
    is_active: true,
    order_of_service: [
      { id: 'item-201', order: 1, time: '10:00 - 10:15', title: 'Call to Worship & Intercession', minister: 'Deacon Stephen Antwi', duration: '15 min' },
      { id: 'item-202', order: 2, time: '10:15 - 10:55', title: 'High Praise & Celebratory Worship', minister: 'Minister Kwadwo Boateng & Choir', duration: '40 min' },
      { id: 'item-203', order: 3, time: '10:55 - 11:10', title: 'New Visitors Reception & Church Pulse', minister: 'Lady Pastor Mercy Agyemang', duration: '15 min' },
      { id: 'item-204', order: 4, time: '11:10 - 11:30', title: 'Sacrificial Giving, Tithes & Building Seed', minister: 'Church Finance Board', duration: '20 min' },
      { id: 'item-205', order: 5, time: '11:30 - 12:15', title: 'Ministry of the Word: "Walking in Greater Works"', minister: 'Prophet Elisha K. Richard', duration: '45 min' },
      { id: 'item-206', order: 6, time: '12:15 - 12:30', title: 'Altar Call, Healing Ministry & Benediction', minister: 'Prophet Elisha & Pastoral Team', duration: '15 min' },
    ],
  },
  {
    id: 'srv-003',
    name: 'Midweek Miracle & Teaching Service',
    type: 'midweek',
    day_of_week: 'Wednesday',
    start_time: '18:30',
    end_time: '20:30',
    venue: 'Main Cathedral Sanctuary, Joma',
    service_leader: 'Elder Kenneth Asare',
    preacher: 'Pastor David Osei-Tutu',
    worship_leader: 'Brother Prince Lamptey',
    expected_attendance: 120,
    description: 'In-depth biblical expository verse-by-verse teaching and prayer for signs and wonders.',
    is_active: true,
    order_of_service: [
      { id: 'item-301', order: 1, time: '18:30 - 18:50', title: 'Opening Intercession for the Nation & Families', minister: 'Prayer Warriors Team', duration: '20 min' },
      { id: 'item-302', order: 2, time: '18:50 - 19:15', title: 'Devotional Hymns & Heartfelt Worship', minister: 'Worship Lead', duration: '25 min' },
      { id: 'item-303', order: 3, time: '19:15 - 20:05', title: 'Doctrinal Bible Exegesis & Teaching', minister: 'Pastor David Osei-Tutu', duration: '50 min' },
      { id: 'item-304', order: 4, time: '20:05 - 20:25', title: 'Targeted Deliverance & Miracle Prayers', minister: 'Ministers on Duty', duration: '20 min' },
      { id: 'item-305', order: 5, time: '20:25 - 20:30', title: 'Offering & Blessing Benediction', minister: 'Elder Kenneth Asare', duration: '5 min' },
    ],
  },
  {
    id: 'srv-004',
    name: 'Friday All-Night Deliverance Vigil',
    type: 'prayer',
    day_of_week: 'Friday',
    start_time: '22:00',
    end_time: '04:00',
    venue: 'Main Cathedral Sanctuary, Joma',
    service_leader: 'Pastor Mrs. Grace Appiah',
    preacher: 'Guest Revival Evangelist & Apostle',
    worship_leader: 'Voice of Dominion Night Watch',
    expected_attendance: 200,
    description: 'Intense intercession, midnight prophetic warfare, family deliverance, and breakthroughs.',
    is_active: true,
    order_of_service: [
      { id: 'item-401', order: 1, time: '22:00 - 23:00', title: 'Watchmen Prayer Call & Personal Consecration', minister: 'Evangelism & Prayer Band', duration: '60 min' },
      { id: 'item-402', order: 2, time: '23:00 - 00:00', title: 'Midnight Apostolic Warfare Praise', minister: 'Choir & Percussionists', duration: '60 min' },
      { id: 'item-403', order: 3, time: '00:00 - 01:30', title: 'Midnight Prophetic Word & Breaking Yokes', minister: 'Prophet Elisha K. Richard', duration: '90 min' },
      { id: 'item-404', order: 4, time: '01:30 - 03:00', title: 'Deliverance Lines, Anointing with Oil & Healing', minister: 'Pastoral Council', duration: '90 min' },
      { id: 'item-405', order: 5, time: '03:00 - 04:00', title: 'Sacrificial Midnight Seed & Morning Glory Release', minister: 'Pastor Mrs. Grace Appiah', duration: '60 min' },
    ],
  },
  {
    id: 'srv-005',
    name: 'Youth & Campus Fire Ignite (Generations of Champions)',
    type: 'youth',
    day_of_week: 'Saturday',
    start_time: '16:00',
    end_time: '18:30',
    venue: 'Youth Pavilion & Audio-Visual Hall, Joma',
    service_leader: 'Brother Michael Quaye',
    preacher: 'Youth Pastor & Guest Speaker',
    worship_leader: 'Champions Contemporary Band',
    expected_attendance: 90,
    description: 'Vibrant youth praise, creative arts, career mentoring, and Holy Spirit revival for young adults.',
    is_active: true,
  },
];

export const sampleMinistries: Ministry[] = [
  {
    id: 'min-001',
    name: 'Voice of Dominion (Choir & Worship Team)',
    description: 'Leads the congregation in Spirit-filled praise, adoration, and classical choral anthems.',
    leader_name: 'Minister Kwadwo Boateng',
    assistant_leader_name: 'Sister Gifty Annan',
    meeting_schedule: 'Every Saturday at 4:00 PM',
    status: 'active',
    member_count: 32,
  },
  {
    id: 'min-002',
    name: 'Media, Sound & IT Ministry',
    description: 'Responsible for live broadcasting, sound engineering, multi-camera streaming, and digital assets.',
    leader_name: 'Brother Samuel Darko',
    assistant_leader_name: 'Brother Prince Lamptey',
    meeting_schedule: 'Every Friday at 5:30 PM & Sunday Pre-service',
    status: 'active',
    member_count: 14,
  },
  {
    id: 'min-003',
    name: 'Royal Protocol & Ushers',
    description: 'Greets worshipers, coordinates seating, distributes bulletins, and handles service order.',
    leader_name: 'Deaconess Beatrice Owusu',
    assistant_leader_name: 'Sister Selina Mensah',
    meeting_schedule: '1st & 3rd Saturdays at 3:00 PM',
    status: 'active',
    member_count: 24,
  },
  {
    id: 'min-004',
    name: 'Generations of Champions (Youth & Young Adults)',
    description: 'Equipping teenagers and tertiary students for leadership, purity, and career excellence.',
    leader_name: 'Elder Kenneth Asare',
    assistant_leader_name: 'Sister Jessica Tetteh',
    meeting_schedule: 'Every Sunday at 3:30 PM',
    status: 'active',
    member_count: 58,
  },
  {
    id: 'min-005',
    name: 'Women of Grace (Virtuous Women)',
    description: 'Nurturing godly mothers, wives, and career women in spiritual maturity and home building.',
    leader_name: 'Lady Pastor Mercy Agyemang',
    assistant_leader_name: 'Mama Florence Adjei',
    meeting_schedule: '2nd Saturday of every month at 8:00 AM',
    status: 'active',
    member_count: 76,
  },
  {
    id: 'min-006',
    name: 'Men of Valour (Christian Men Fellowship)',
    description: 'Brotherhood fostering spiritual resilience, economic empowerment, and family leadership.',
    leader_name: 'Elder Joseph Koomson',
    assistant_leader_name: 'Brother Daniel Koranteng',
    meeting_schedule: 'Last Saturday of every month at 7:00 AM',
    status: 'active',
    member_count: 65,
  },
  {
    id: 'min-007',
    name: 'Intercessory Prayer Army',
    description: 'Carrying the church in 24/7 continuous prayer watches, fasting, and deliverance sessions.',
    leader_name: 'Pastor David Osei-Tutu',
    assistant_leader_name: 'Evangelist Paulina Akoto',
    meeting_schedule: 'Tuesdays & Thursdays at 5:00 PM',
    status: 'active',
    member_count: 28,
  },
];

export const sampleSmallGroups: SmallGroup[] = [
  {
    id: 'grp-001',
    name: 'Joma Faith Cell',
    leader_name: 'Elder Kenneth Asare',
    assistant_leader_name: 'Sister Mary Addo',
    meeting_location: 'Near Joma Chief Palace, Joma',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    notes: 'Meets in the compound of Elder Kenneth',
    member_count: 18,
  },
  {
    id: 'grp-002',
    name: 'Ablekuma Central Cell',
    leader_name: 'Deacon Stephen Antwi',
    meeting_location: 'Ablekuma Curve, Opposite Presby Church',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    notes: 'Active cell group with steady growth',
    member_count: 22,
  },
  {
    id: 'grp-003',
    name: 'Weija Victory Group',
    leader_name: 'Sister Mercy Mensah',
    meeting_location: 'Weija Junction, Near Barrier',
    meeting_day: 'Thursday',
    meeting_time: '18:30',
    notes: 'Focus on family Bible study',
    member_count: 16,
  },
  {
    id: 'grp-004',
    name: 'Anyaa Fellowship Hub',
    leader_name: 'Brother Michael Quaye',
    meeting_location: 'Anyaa Market area, House No. 44B',
    meeting_day: 'Thursday',
    meeting_time: '19:00',
    notes: 'Young professionals and families',
    member_count: 19,
  },
];

export const sampleMembers: Member[] = [
  {
    id: 'mem-001',
    member_id: 'GWCC-000001',
    tithe_number: 'T-1042',
    first_name: 'Kwame',
    middle_name: 'Owusu',
    last_name: 'Mensah',
    gender: 'male',
    date_of_birth: '1988-04-12',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Senior Civil Engineer',
    employer: 'Ghana Highway Authority',
    education: 'BSc Civil Engineering (KNUST)',
    phone: '+233 24 456 1234',
    alternative_phone: '+233 20 987 6543',
    email: 'k.mensah@ghanahighways.gov.gh',
    residential_address: 'Plot 42, Joma New Site, Near Top Pharmacy',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4921',
    profile_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2021-03-15',
    first_visit_date: '2021-01-10',
    baptism_status: true,
    baptism_date: '2021-06-20',
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-006',
    ministry_name: 'Men of Valour (Christian Men Fellowship)',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    leadership_position: 'Men Fellowship Secretary',
    emergency_name: 'Dr. Evelyn Mensah',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 24 555 9876',
    notes: 'Pillar of the church, consistent tither, and active cell organizer.',
    is_archived: false,
    created_at: '2021-03-15T10:00:00Z',
    updated_at: '2026-09-01T14:20:00Z',
  },
  {
    id: 'mem-002',
    member_id: 'GWCC-000002',
    tithe_number: 'T-1043',
    first_name: 'Abena',
    middle_name: 'Serwaa',
    last_name: 'Osei',
    gender: 'female',
    date_of_birth: '1993-09-28',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Pharmacist',
    employer: 'Ernest Chemists Ltd',
    education: 'PharmD (University of Ghana)',
    phone: '+233 20 876 5432',
    email: 'abena.osei@gmail.com',
    residential_address: 'House No. 12, Ablekuma Central, Accra',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-201-9943',
    profile_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2022-01-09',
    first_visit_date: '2021-11-28',
    baptism_status: true,
    baptism_date: '2022-04-17',
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-001',
    ministry_name: 'Voice of Dominion (Choir & Worship Team)',
    small_group_id: 'grp-002',
    small_group_name: 'Ablekuma Central Cell',
    leadership_position: 'Soprano Section Leader',
    emergency_name: 'Kofi Osei',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 24 777 8899',
    notes: 'Very gifted soloist, faithfully attends choir rehearsals every Saturday.',
    is_archived: false,
    created_at: '2022-01-09T11:00:00Z',
    updated_at: '2026-09-10T16:00:00Z',
  },
  {
    id: 'mem-003',
    member_id: 'GWCC-000003',
    tithe_number: 'T-1044',
    first_name: 'Kofi',
    middle_name: 'Badu',
    last_name: 'Asante',
    gender: 'male',
    date_of_birth: '1997-11-05',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Software Engineer',
    employer: 'Hubtel Ghana',
    education: 'BSc Computer Science (Ashesi)',
    phone: '+233 55 123 9876',
    email: 'kofi.asante.tech@gmail.com',
    residential_address: 'Anyaa West, Near Pentecost Church',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-190-2345',
    profile_photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2023-05-21',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-002',
    ministry_name: 'Media, Sound & IT Ministry',
    small_group_id: 'grp-004',
    small_group_name: 'Anyaa Fellowship Hub',
    leadership_position: 'Live Stream Coordinator',
    emergency_name: 'Gladys Asante',
    emergency_relationship: 'Mother',
    emergency_phone: '+233 24 333 1122',
    notes: 'Handles church YouTube live stream and social media clips.',
    is_archived: false,
    created_at: '2023-05-21T09:30:00Z',
    updated_at: '2026-09-15T12:00:00Z',
  },
  {
    id: 'mem-004',
    member_id: 'GWCC-000004',
    tithe_number: 'T-1045',
    first_name: 'Esi',
    middle_name: 'Akua',
    last_name: 'Darko',
    gender: 'female',
    date_of_birth: '1985-02-14',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'High School Head of Department',
    employer: 'Ghana Education Service',
    education: 'M.Ed Curriculum & Instruction',
    phone: '+233 24 999 4433',
    email: 'esi.darko85@yahoo.com',
    residential_address: 'Weija Hills, Near Barrier Shell',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-175-8812',
    profile_photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2020-02-16',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-005',
    ministry_name: 'Women of Grace (Virtuous Women)',
    small_group_id: 'grp-003',
    small_group_name: 'Weija Victory Group',
    leadership_position: 'Sunday School Teacher Coordinator',
    emergency_name: 'Patrick Darko',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 20 444 8877',
    notes: 'Devoted children and women ministry leader.',
    is_archived: false,
    created_at: '2020-02-16T10:00:00Z',
    updated_at: '2026-09-02T11:00:00Z',
  },
  {
    id: 'mem-005',
    member_id: 'GWCC-000005',
    tithe_number: 'T-1046',
    first_name: 'Emmanuel',
    middle_name: 'Nana',
    last_name: 'Boateng',
    gender: 'male',
    date_of_birth: '1991-08-30',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Wholesale Trader',
    employer: 'Boateng Ventures Joma',
    phone: '+233 24 333 5566',
    email: 'emmanuel.boateng.joma@gmail.com',
    residential_address: 'Joma Main Street, Beside Police Post',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-2004',
    profile_photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2021-08-22',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-003',
    ministry_name: 'Royal Protocol & Ushers',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    leadership_position: 'Head of Ushering - 1st Service',
    emergency_name: 'Mercy Boateng',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 24 666 9911',
    notes: 'Consistent giver, pledged GH₵ 5,000 to building project.',
    is_archived: false,
    created_at: '2021-08-22T08:00:00Z',
    updated_at: '2026-09-18T10:30:00Z',
  },
  {
    id: 'mem-006',
    member_id: 'GWCC-000006',
    tithe_number: 'T-1047',
    first_name: 'Priscilla',
    middle_name: 'Ama',
    last_name: 'Adjei',
    gender: 'female',
    date_of_birth: '2001-09-24', // Birthday tomorrow or today for reminder widget!
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Undergraduate Nursing Student',
    employer: 'University of Ghana Nursing School',
    education: 'BSc Nursing (In Progress)',
    phone: '+233 54 888 1234',
    email: 'priscilla.adjei@st.ug.edu.gh',
    residential_address: 'Ablekuma Fanmilk, Near Filling Station',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-199-4455',
    profile_photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2023-01-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-004',
    ministry_name: 'Generations of Champions (Youth & Young Adults)',
    small_group_id: 'grp-002',
    small_group_name: 'Ablekuma Central Cell',
    leadership_position: 'Youth Outreach Secretary',
    emergency_name: 'Francis Adjei',
    emergency_relationship: 'Father',
    emergency_phone: '+233 20 111 4455',
    notes: 'Upcoming birthday! Active in campus fellowship outreach.',
    is_archived: false,
    created_at: '2023-01-15T09:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'mem-007',
    member_id: 'GWCC-000007',
    tithe_number: 'T-1048',
    first_name: 'Samuel',
    middle_name: 'Kweku',
    last_name: 'Appiah',
    gender: 'male',
    date_of_birth: '1976-12-10',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Branch Manager',
    employer: 'GCB Bank PLC',
    education: 'MBA Finance (UGBS)',
    phone: '+233 24 700 8822',
    email: 'sappiah@gcbbank.com.gh',
    residential_address: 'Weija Residential Area, Block D',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-172-5501',
    profile_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    membership_date: '2019-10-06',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-006',
    ministry_name: 'Men of Valour (Christian Men Fellowship)',
    small_group_id: 'grp-003',
    small_group_name: 'Weija Victory Group',
    leadership_position: 'Church Audit Committee Chairman',
    emergency_name: 'Grace Appiah',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 24 888 2211',
    notes: 'Senior elder and advisor on financial structures.',
    is_archived: false,
    created_at: '2019-10-06T10:00:00Z',
    updated_at: '2026-09-12T15:00:00Z',
  },
  {
    id: 'mem-008',
    member_id: 'GWCC-000008',
    first_name: 'Dorothy',
    last_name: 'Ansah',
    gender: 'female',
    date_of_birth: '1995-09-25',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Graphic Designer',
    phone: '+233 26 444 3322',
    email: 'dorothy.ansah@gmail.com',
    residential_address: 'Joma Old Town, Near Anglican School',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-184-1100',
    status: 'new_member',
    membership_date: '2026-08-10',
    first_visit_date: '2026-07-15',
    baptism_status: false,
    salvation_status: true,
    membership_class_completed: false,
    ministry_id: 'min-002',
    ministry_name: 'Media, Sound & IT Ministry',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    emergency_name: 'Kwame Ansah',
    emergency_relationship: 'Brother',
    emergency_phone: '+233 24 111 8899',
    notes: 'Recently finished new believers orientation. Awaiting water baptism.',
    is_archived: false,
    created_at: '2026-08-10T11:00:00Z',
    updated_at: '2026-09-05T09:00:00Z',
  },
  {
    id: 'mem-009',
    member_id: 'GWCC-000009',
    first_name: 'Richmond',
    middle_name: 'Kofi',
    last_name: 'Tetteh',
    gender: 'male',
    date_of_birth: '2003-05-18',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Apprentice Auto-Electrician',
    phone: '+233 59 777 2233',
    email: 'richmond.k.tetteh@gmail.com',
    residential_address: 'Joma Chief Palace Junction',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-5590',
    profile_photo_url: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=150&auto=format&fit=crop&q=80',
    status: 'new_convert',
    membership_date: '2026-09-06',
    first_visit_date: '2026-08-30',
    baptism_status: false,
    salvation_status: true,
    membership_class_completed: false,
    ministry_id: 'min-004',
    ministry_name: 'Generations of Champions (Youth & Young Adults)',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    emergency_name: 'Kojo Tetteh',
    emergency_relationship: 'Uncle',
    emergency_phone: '+233 24 999 1100',
    notes: 'Gave life to Christ during August Evangelism Outreach. Enrolled in New Believers Foundation Class.',
    is_archived: false,
    created_at: '2026-09-06T10:30:00Z',
    updated_at: '2026-09-20T12:00:00Z',
  },
  {
    id: 'mem-010',
    member_id: 'GWCC-000010',
    tithe_number: 'T-1049',
    first_name: 'Isaac',
    middle_name: 'Mensah',
    last_name: 'Quaye',
    gender: 'male',
    date_of_birth: '1984-07-19',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Logistics Supervisor',
    phone: '+233 27 654 3210',
    email: 'imquaye@logisticsgh.com',
    residential_address: 'Anyaa Last Stop, Near Clinic',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-192-3344',
    profile_photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    status: 'inactive',
    membership_date: '2020-11-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-006',
    ministry_name: 'Men of Valour (Christian Men Fellowship)',
    small_group_id: 'grp-004',
    small_group_name: 'Anyaa Fellowship Hub',
    emergency_name: 'Hannah Quaye',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 20 888 7766',
    notes: 'Temporarily deployed to Takoradi harbor on assignment. Pastoral care phone checks ongoing.',
    is_archived: false,
    created_at: '2020-11-15T09:00:00Z',
    updated_at: '2026-08-20T14:00:00Z',
  },
  {
    id: 'mem-011',
    member_id: 'GWCC-000011',
    tithe_number: 'T-1002',
    first_name: 'Elder Joseph',
    last_name: 'Koomson',
    gender: 'male',
    date_of_birth: '1970-03-22',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Director of Education',
    phone: '+233 24 222 7788',
    email: 'j.koomson@gwccgh.org',
    residential_address: 'Joma Estate, Gate 3, House 14',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-0012',
    profile_photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'leader',
    membership_date: '2018-01-14',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-006',
    ministry_name: 'Men of Valour (Christian Men Fellowship)',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    leadership_position: 'Presiding Elder & Men Fellowship President',
    emergency_name: 'Mrs. Cynthia Koomson',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 20 333 4455',
    notes: 'Founding elder of Joma Assembly. Oversees pastoral elder board and welfare allocations.',
    is_archived: false,
    created_at: '2018-01-14T08:00:00Z',
    updated_at: '2026-09-22T08:30:00Z',
  },
  {
    id: 'mem-011',
    member_id: 'GWCC-000011',
    tithe_number: 'T-1052',
    first_name: 'Clara',
    middle_name: '',
    last_name: 'Tamekloe Gaewornu',
    gender: 'female',
    date_of_birth: '1985-06-18',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'General Secretary & Church Registrar',
    employer: 'Greater Works City Church',
    education: 'MPA Public Administration (GIMPA)',
    phone: '+233 24 777 8899',
    email: 'clara.gaewornu@greaterworkscitychurch.org',
    residential_address: 'House 28, Joma Estate, Near Pentecost Junction',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4921',
    profile_photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'leader',
    membership_date: '2019-02-10',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-003',
    ministry_name: 'Royal Protocol & Ushers',
    small_group_id: 'grp-001',
    small_group_name: 'Joma Faith Cell',
    leadership_position: 'General Secretary',
    emergency_name: 'Mr. Selorm Gaewornu',
    emergency_relationship: 'Spouse',
    emergency_phone: '+233 20 555 7711',
    notes: 'General Secretary of Greater Works City Church. Directs the central secretariat, administration, and official correspondence.',
    is_archived: false,
    created_at: '2019-02-10T08:00:00Z',
    updated_at: '2026-09-26T08:00:00Z',
  },
];

export const sampleVisitors: Visitor[] = [
  {
    id: 'vis-001',
    full_name: 'Kwabena Yeboah',
    gender: 'male',
    phone: '+233 24 888 7766',
    email: 'k.yeboah@gmail.com',
    address: 'Ablekuma Fanmilk, Near White House',
    gps_address: 'GA-198-3312',
    visit_date: '2026-09-20',
    service_attended: 'Sunday 2nd Service (Celebration Service)',
    invited_by: 'Kwame Mensah (GWCC-000001)',
    how_heard: 'Friend / Family',
    prayer_request: 'Praying for open doors for relocation visa and peace in the family.',
    follow_up_status: 'follow_up_required',
    assigned_to_name: 'Pastor David Osei-Tutu',
    notes: 'Expressed strong interest in joining the choir. Needs pastoral call this week.',
    created_at: '2026-09-20T12:45:00Z',
    updated_at: '2026-09-21T09:00:00Z',
  },
  {
    id: 'vis-002',
    full_name: 'Joyce Addo',
    gender: 'female',
    phone: '+233 20 444 3311',
    email: 'joyce.addo99@yahoo.com',
    address: 'Joma New Town, House 15',
    gps_address: 'GA-183-7721',
    visit_date: '2026-09-20',
    service_attended: 'Sunday 1st Service (Prophetic Encounter)',
    invited_by: 'Church Banner on Joma High Road',
    how_heard: 'Roadside Banner',
    prayer_request: 'Healing of long-standing chest condition.',
    follow_up_status: 'new',
    assigned_to_name: 'Lady Pastor Mercy Agyemang',
    notes: 'Moved into Joma two weeks ago looking for a Spirit-filled church.',
    created_at: '2026-09-20T09:40:00Z',
    updated_at: '2026-09-20T09:40:00Z',
  },
  {
    id: 'vis-003',
    full_name: 'Daniel Nii Ayi',
    gender: 'male',
    phone: '+233 55 999 0011',
    address: 'Weija Barrier, Behind Melcom',
    visit_date: '2026-09-13',
    service_attended: 'Sunday 2nd Service (Celebration Service)',
    invited_by: 'Kofi Asante (GWCC-000003)',
    how_heard: 'Friend / Family',
    prayer_request: 'Career advancement and business expansion.',
    follow_up_status: 'contacted',
    assigned_to_name: 'Elder Kenneth Asare',
    notes: 'Called on Monday 14th Sept. Visited again on Friday all-night.',
    created_at: '2026-09-13T12:30:00Z',
    updated_at: '2026-09-16T14:15:00Z',
  },
  {
    id: 'vis-004',
    full_name: 'Grace Serwaa Tetteh',
    gender: 'female',
    phone: '+233 24 122 3456',
    email: 'graceserwaa@hotmail.com',
    address: 'Anyaa Market, Accra',
    visit_date: '2026-08-30',
    service_attended: 'Sunday 2nd Service',
    invited_by: 'Sister Jessica Tetteh',
    how_heard: 'Church Evangelism Outreach',
    prayer_request: 'Academic success in licensure examination.',
    follow_up_status: 'returning_visitor',
    assigned_to_name: 'Lady Pastor Mercy Agyemang',
    notes: 'Attended 3 consecutive Sundays, ready for conversion to member!',
    created_at: '2026-08-30T12:00:00Z',
    updated_at: '2026-09-18T10:00:00Z',
  },
];

export const sampleAttendance: AttendanceRecord[] = [
  {
    id: 'att-001',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-20',
    member_id: 'mem-001',
    member_name: 'Kwame Owusu Mensah',
    check_in_time: '2026-09-20T07:22:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-002',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-20',
    member_id: 'mem-004',
    member_name: 'Esi Akua Darko',
    check_in_time: '2026-09-20T07:28:00Z',
    check_in_method: 'manual',
    status: 'present',
  },
  {
    id: 'att-003',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-002',
    member_name: 'Abena Serwaa Osei',
    check_in_time: '2026-09-20T09:45:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-004',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-003',
    member_name: 'Kofi Badu Asante',
    check_in_time: '2026-09-20T09:50:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-005',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-005',
    member_name: 'Emmanuel Nana Boateng',
    check_in_time: '2026-09-20T09:30:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-006',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-006',
    member_name: 'Priscilla Ama Adjei',
    check_in_time: '2026-09-20T09:58:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-007',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    visitor_id: 'vis-001',
    visitor_name: 'Kwabena Yeboah (Visitor)',
    person_name: 'Kwabena Yeboah',
    person_type: 'visitor',
    check_in_time: '2026-09-20T10:15:00Z',
    check_in_method: 'manual',
    status: 'present',
  },
  {
    id: 'att-008',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-20',
    member_id: 'mem-008',
    member_name: 'Dorothy Ansah',
    person_name: 'Dorothy Ansah',
    person_type: 'member',
    check_in_time: '2026-09-20T07:15:00Z',
    check_in_method: 'qr_code',
    status: 'present',
  },
  {
    id: 'att-009',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-009',
    member_name: 'Richmond Kofi Tetteh',
    person_name: 'Richmond Kofi Tetteh',
    person_type: 'member',
    check_in_time: '2026-09-20T09:40:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-010',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    member_id: 'mem-011',
    member_name: 'Elder Joseph Koomson',
    person_name: 'Elder Joseph Koomson',
    person_type: 'member',
    check_in_time: '2026-09-20T09:20:00Z',
    check_in_method: 'manual',
    status: 'present',
  },
  // Previous Sunday: 2026-09-13
  {
    id: 'att-011',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-13',
    member_id: 'mem-001',
    member_name: 'Kwame Owusu Mensah',
    person_name: 'Kwame Owusu Mensah',
    person_type: 'member',
    check_in_time: '2026-09-13T07:20:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-012',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-13',
    member_id: 'mem-002',
    member_name: 'Abena Serwaa Osei',
    person_name: 'Abena Serwaa Osei',
    person_type: 'member',
    check_in_time: '2026-09-13T09:40:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-013',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-13',
    member_id: 'mem-003',
    member_name: 'Kofi Badu Asante',
    person_name: 'Kofi Badu Asante',
    person_type: 'member',
    check_in_time: '2026-09-13T09:48:00Z',
    check_in_method: 'search',
    status: 'present',
  },
  {
    id: 'att-014',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-13',
    visitor_id: 'vis-003',
    visitor_name: 'Daniel Nii Ayi (Visitor)',
    person_name: 'Daniel Nii Ayi',
    person_type: 'visitor',
    check_in_time: '2026-09-13T10:10:00Z',
    check_in_method: 'manual',
    status: 'present',
  },
];

export const sampleHeadcounts: HeadcountRecord[] = [
  {
    id: 'hc-20260920-srv001',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-20',
    men: 72,
    women: 104,
    youth: 38,
    children: 45,
    visitors: 12,
    ushers_protocol: 14,
    online_viewers: 65,
    total_auditorium: 285,
    notes: 'Spirit-filled prophetic service. Strong youth presence in first service.',
    counted_by: 'Deacon Kwesi Appiah (Head Usher)',
    created_at: '2026-09-20T08:50:00Z',
  },
  {
    id: 'hc-20260920-srv002',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-20',
    men: 94,
    women: 146,
    youth: 62,
    children: 58,
    visitors: 24,
    ushers_protocol: 16,
    online_viewers: 110,
    total_auditorium: 400,
    notes: 'Sanctuary filled to capacity. Overflow canopy set up at church courtyard.',
    counted_by: 'Sister Jessica Tetteh (Protocol Lead)',
    created_at: '2026-09-20T11:45:00Z',
  },
  {
    id: 'hc-20260916-srv003',
    service_id: 'srv-003',
    service_name: 'Midweek Encounter & Communion Service',
    date: '2026-09-16',
    men: 38,
    women: 54,
    youth: 22,
    children: 18,
    visitors: 6,
    ushers_protocol: 8,
    online_viewers: 42,
    total_auditorium: 146,
    notes: 'Communion service with deep worship and prayer.',
    counted_by: 'Elder Kenneth Asare',
    created_at: '2026-09-16T20:20:00Z',
  },
  {
    id: 'hc-20260913-srv001',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-13',
    men: 68,
    women: 98,
    youth: 35,
    children: 40,
    visitors: 10,
    ushers_protocol: 14,
    online_viewers: 58,
    total_auditorium: 265,
    notes: 'First service with testimony hour.',
    counted_by: 'Deacon Kwesi Appiah',
    created_at: '2026-09-13T08:45:00Z',
  },
  {
    id: 'hc-20260913-srv002',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-13',
    men: 90,
    women: 140,
    youth: 58,
    children: 52,
    visitors: 21,
    ushers_protocol: 16,
    online_viewers: 95,
    total_auditorium: 377,
    notes: 'Wonderful celebration service.',
    counted_by: 'Sister Jessica Tetteh',
    created_at: '2026-09-13T11:40:00Z',
  },
  {
    id: 'hc-20260906-srv001',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-09-06',
    men: 65,
    women: 92,
    youth: 32,
    children: 38,
    visitors: 8,
    ushers_protocol: 12,
    online_viewers: 52,
    total_auditorium: 247,
    notes: 'Communion Sunday first service.',
    counted_by: 'Deacon Kwesi Appiah',
    created_at: '2026-09-06T08:40:00Z',
  },
  {
    id: 'hc-20260906-srv002',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-09-06',
    men: 88,
    women: 135,
    youth: 55,
    children: 50,
    visitors: 19,
    ushers_protocol: 15,
    online_viewers: 90,
    total_auditorium: 362,
    notes: 'Monthly Thanksgiving service.',
    counted_by: 'Sister Jessica Tetteh',
    created_at: '2026-09-06T11:35:00Z',
  },
  {
    id: 'hc-20260830-srv001',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service (Prophetic Encounter)',
    date: '2026-08-30',
    men: 70,
    women: 100,
    youth: 34,
    children: 42,
    visitors: 11,
    ushers_protocol: 14,
    online_viewers: 60,
    total_auditorium: 271,
    notes: 'Evangelism emphasis Sunday.',
    counted_by: 'Deacon Kwesi Appiah',
    created_at: '2026-08-30T08:50:00Z',
  },
  {
    id: 'hc-20260830-srv002',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service (Celebration Service)',
    date: '2026-08-30',
    men: 92,
    women: 142,
    youth: 60,
    children: 55,
    visitors: 22,
    ushers_protocol: 16,
    online_viewers: 105,
    total_auditorium: 387,
    notes: 'High visitor turnout from Joma high street evangelism.',
    counted_by: 'Sister Jessica Tetteh',
    created_at: '2026-08-30T11:45:00Z',
  },
];

export const sampleGiving: GivingRecord[] = [
  {
    id: 'giv-001',
    member_id: 'mem-001',
    member_name: 'Kwame Owusu Mensah',
    category: 'Tithe',
    amount: 1450.0,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MM-20260920-8812',
    service_id: 'srv-001',
    service_name: 'Sunday 1st Service',
    notes: 'September 2026 Tithe payment',
    created_at: '2026-09-20T08:45:00Z',
  },
  {
    id: 'giv-002',
    member_id: 'mem-002',
    member_name: 'Abena Serwaa Osei',
    category: 'Tithe',
    amount: 950.0,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'mobile_money',
    payment_channel: 'Telecel Cash',
    reference_number: 'TC-992384',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service',
    notes: 'Tithe',
    created_at: '2026-09-20T11:20:00Z',
  },
  {
    id: 'giv-003',
    donor_name: 'Sunday 2nd Service Congregation',
    category: 'Offering',
    amount: 4860.0,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'cash',
    payment_channel: 'Cash Bowl Collection',
    reference_number: 'CSH-OFF-20260920',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service',
    notes: 'General congregational open basket offering',
    created_at: '2026-09-20T12:40:00Z',
  },
  {
    id: 'giv-004',
    member_id: 'mem-005',
    member_name: 'Emmanuel Nana Boateng',
    category: 'Building Fund',
    amount: 1000.0,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MM-4912001',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service',
    notes: 'Cathedral Expansion project installment',
    created_at: '2026-09-20T12:00:00Z',
  },
  {
    id: 'giv-005',
    member_id: 'mem-007',
    member_name: 'Samuel Kweku Appiah',
    category: 'Tithe',
    amount: 2200.0,
    currency: 'GHS',
    date: '2026-09-18',
    payment_method: 'bank_transfer',
    payment_channel: 'GCB Bank Transfer',
    reference_number: 'GCB-TRF-0918-01',
    notes: 'Direct account transfer tithe',
    created_at: '2026-09-18T16:30:00Z',
  },
  {
    id: 'giv-006',
    member_id: 'mem-003',
    member_name: 'Kofi Badu Asante',
    category: 'Thanksgiving',
    amount: 800.0,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MM-9944112',
    service_id: 'srv-002',
    service_name: 'Sunday 2nd Service',
    notes: 'Thanksgiving for software promotion at work',
    created_at: '2026-09-20T11:45:00Z',
  },
];

export const samplePledgeCampaigns: PledgeCampaign[] = [
  {
    id: 'cmp-001',
    name: 'Cathedral Expansion & Roofing Project 2026',
    target_amount: 250000.0,
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    description: 'Extending the main auditorium by 500 seats with acoustic ceiling and sound dampening.',
    is_active: true,
  },
  {
    id: 'cmp-002',
    name: 'Evangelism Bus & Sound Mobile Outreach',
    target_amount: 80000.0,
    start_date: '2026-06-01',
    end_date: '2026-11-30',
    description: 'Procurement of a 30-seater Toyota Coaster bus for church shuttles and crusades.',
    is_active: true,
  },
];

export const samplePledges: PledgeRecord[] = [
  {
    id: 'plg-001',
    campaign_id: 'cmp-001',
    campaign_name: 'Cathedral Expansion & Roofing Project 2026',
    member_id: 'mem-001',
    member_name: 'Kwame Owusu Mensah',
    member_phone: '+233 24 456 1234',
    amount_pledged: 10000.0,
    amount_paid: 6000.0,
    balance: 4000.0,
    start_date: '2026-01-15',
    due_date: '2026-12-15',
    status: 'partially_paid',
    notes: 'Paying GH₵ 1,000 monthly',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'plg-002',
    campaign_id: 'cmp-001',
    campaign_name: 'Cathedral Expansion & Roofing Project 2026',
    member_id: 'mem-005',
    member_name: 'Emmanuel Nana Boateng',
    member_phone: '+233 24 333 5566',
    amount_pledged: 5000.0,
    amount_paid: 5000.0,
    balance: 0.0,
    start_date: '2026-02-01',
    due_date: '2026-09-30',
    status: 'completed',
    notes: 'Paid in full via MTN MoMo',
    created_at: '2026-02-01T12:00:00Z',
  },
  {
    id: 'plg-003',
    campaign_id: 'cmp-002',
    campaign_name: 'Evangelism Bus & Sound Mobile Outreach',
    member_id: 'mem-007',
    member_name: 'Samuel Kweku Appiah',
    member_phone: '+233 24 700 8822',
    amount_pledged: 7500.0,
    amount_paid: 3500.0,
    balance: 4000.0,
    start_date: '2026-06-10',
    due_date: '2026-11-25',
    status: 'partially_paid',
    notes: 'Pledge for vehicle engine overhaul contribution',
    created_at: '2026-06-10T14:00:00Z',
  },
];

export const sampleExpenses: ExpenseRecord[] = [
  {
    id: 'exp-001',
    category: 'Utilities',
    amount: 1850.0,
    currency: 'GHS',
    date: '2026-09-15',
    account: 'Mobile Money Account',
    payment_method: 'mobile_money',
    reference_number: 'ECG-PREPAID-9921',
    description: 'ECG Electricity prepaid purchase for church auditorium and AC units',
    approved_by: 'Prophet Elisha K. Richard',
    created_at: '2026-09-15T09:00:00Z',
  },
  {
    id: 'exp-002',
    category: 'Salaries/Allowances',
    amount: 3200.0,
    currency: 'GHS',
    date: '2026-09-01',
    account: 'Bank Account (Zenith Bank)',
    payment_method: 'bank_transfer',
    reference_number: 'SAL-SEP-001',
    description: 'Administrative assistant and church premises caretaker monthly stipends',
    approved_by: 'Senior Pastor & Finance Officer',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'exp-003',
    category: 'Media & Production',
    amount: 920.0,
    currency: 'GHS',
    date: '2026-09-10',
    account: 'Mobile Money Account',
    payment_method: 'mobile_money',
    reference_number: 'MM-EXP-0910',
    description: 'High-speed 4G internet bundle renewal for live-streaming Sunday services',
    approved_by: 'Kofi Mensah-Bonsu (Admin)',
    created_at: '2026-09-10T11:00:00Z',
  },
];

export const sampleEvents: ChurchEvent[] = [
  {
    id: 'evt-001',
    title: 'Supernatural Breakthrough Convention 2026',
    description: '3 Days of apostolic outpouring, healing, financial release, and prophetic impartation with guests from across Greater Accra.',
    theme: 'Possessing Your Possessions',
    theme_scripture: 'Obadiah 1:17',
    event_type: 'conference',
    start_date: '2026-10-14',
    end_date: '2026-10-16',
    start_time: '18:00',
    end_time: '21:30',
    venue: 'GWCC Main Sanctuary, Joma, Accra',
    organizer: 'GWCC Pastoral Board',
    speaker: 'Prophet Elisha K. Richard & Bishop Isaac Mensah',
    ministry_name: 'Pastoral & Ministerial Council',
    expected_attendance: 650,
    budget: 15000,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 148,
    banner_color: 'amber',
    attendees: [
      { id: 'att-1', name: 'Kwame Owusu Mensah', phone: '+233 24 456 1234', role: 'Protocol', registered_at: '2026-09-18T10:00:00Z', checked_in: false },
      { id: 'att-2', name: 'Abena Serwaa Osei', phone: '+233 20 890 5678', role: 'Usher', registered_at: '2026-09-19T14:30:00Z', checked_in: false },
      { id: 'att-3', name: 'Kofi Badu Asante', phone: '+233 24 123 9876', role: 'Sound/Media', registered_at: '2026-09-20T09:15:00Z', checked_in: false },
      { id: 'att-4', name: 'Sister Grace Addo', phone: '+233 27 555 4321', role: 'Praise Team', registered_at: '2026-09-21T11:00:00Z', checked_in: false },
      { id: 'att-5', name: 'Emmanuel Nana Boateng', phone: '+233 24 333 5566', role: 'Volunteer', registered_at: '2026-09-22T16:45:00Z', checked_in: false },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-002',
    title: 'Mega Joma Community Medical & Soul Outreach',
    description: 'Free general health screening, malaria checks, blood pressure monitoring, deworming for children, free clothing distribution, and house-to-house street evangelism.',
    theme: 'Love In Action & Saving Joma',
    theme_scripture: 'Matthew 25:40',
    event_type: 'outreach',
    start_date: '2026-10-03',
    end_date: '2026-10-03',
    start_time: '08:00',
    end_time: '16:00',
    venue: 'Joma Community School Park, Accra',
    organizer: 'GWCC Evangelism & Welfare Ministry',
    speaker: 'Dr. Kwesi Appiah & Pastor David Osei-Tutu',
    ministry_name: 'Evangelism & Outreach Ministry',
    expected_attendance: 400,
    budget: 8500,
    status: 'upcoming',
    requires_registration: false,
    registration_count: 62,
    banner_color: 'emerald',
    attendees: [
      { id: 'att-6', name: 'Dr. Samuel Kweku Appiah', phone: '+233 24 700 8822', role: 'Medical Team Lead', registered_at: '2026-09-15T08:00:00Z', checked_in: false },
      { id: 'att-7', name: 'Mercy Afia Ofori', phone: '+233 54 888 1234', role: 'Welfare Distribution', registered_at: '2026-09-16T12:00:00Z', checked_in: false },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-003',
    title: 'Youth Worship Night: Flames of Fire',
    description: 'Passionate uncensored praise, intense prophetic worship, spoken word poetry, and prayer sessions for high school students, tertiary students, and young working professionals.',
    theme: 'Set Ablaze For Christ',
    theme_scripture: 'Hebrews 1:7',
    event_type: 'youth',
    start_date: '2026-09-26',
    end_date: '2026-09-26',
    start_time: '17:00',
    end_time: '20:30',
    venue: 'GWCC Main Sanctuary',
    organizer: 'Generations of Champions Youth',
    speaker: 'Elder Kenneth Asare & Praise Harvest',
    ministry_name: 'Youth Ministry (Generations of Champions)',
    expected_attendance: 150,
    budget: 3200,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 85,
    banner_color: 'purple',
    attendees: [
      { id: 'att-8', name: 'Richmond Kofi Tetteh', phone: '+233 59 777 2233', role: 'Usher', registered_at: '2026-09-22T14:00:00Z', checked_in: false },
      { id: 'att-9', name: 'Sister Grace Addo', phone: '+233 27 555 4321', role: 'Lead Vocalist', registered_at: '2026-09-23T10:30:00Z', checked_in: false },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'September Miracle & Deliverance All-Night Vigil',
    description: 'An aggressive night of midnight breakthrough prayer, spiritual warfare, breaking territorial ancestral altars, and anointing to enter October victorious.',
    theme: 'Possessing The Gates of the New Month',
    theme_scripture: 'Isaiah 10:27',
    event_type: 'all_night',
    start_date: '2026-09-25',
    end_date: '2026-09-26',
    start_time: '22:00',
    end_time: '04:30',
    venue: 'GWCC Main Sanctuary, Joma',
    organizer: 'Prayer & Intercession Warriors',
    speaker: 'Pastor David Osei-Tutu & Prophet Elisha K. Richard',
    ministry_name: 'Prayer & Intercession Ministry',
    expected_attendance: 280,
    budget: 2500,
    status: 'ongoing',
    requires_registration: false,
    registration_count: 110,
    banner_color: 'rose',
    attendees: [
      { id: 'att-10', name: 'Elder Joseph Koomson', phone: '+233 20 111 2233', role: 'Intercessor Lead', registered_at: '2026-09-24T08:00:00Z', checked_in: true },
      { id: 'att-11', name: 'Kofi Badu Asante', phone: '+233 24 123 9876', role: 'Sound Operator', registered_at: '2026-09-24T18:00:00Z', checked_in: true },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'Women of Grace Kingdom Daughters Summit',
    description: 'An inspiring day of teaching on godly womanhood, marital harmony, entrepreneurial mastery, health wellness, and spiritual intercession for our children.',
    theme: 'Virtuous, Anointed & Purpose-Driven',
    theme_scripture: 'Proverbs 31:29-30',
    event_type: 'special',
    start_date: '2026-10-24',
    end_date: '2026-10-24',
    start_time: '09:00',
    end_time: '15:30',
    venue: 'GWCC Main Sanctuary, Joma',
    organizer: 'Women of Grace Ministry',
    speaker: 'Rev. Mrs. Grace Richard & Lady Rev. Comfort Mensah',
    ministry_name: 'Women of Grace (Women Fellowship)',
    expected_attendance: 220,
    budget: 6500,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 94,
    banner_color: 'pink',
    attendees: [
      { id: 'att-12', name: 'Abena Serwaa Osei', phone: '+233 20 890 5678', role: 'Hostess Coordinator', registered_at: '2026-09-20T10:00:00Z', checked_in: false },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-006',
    title: 'Men of Valour Business & Leadership Summit',
    description: 'Empowerment breakfast session addressing Christian financial planning, building sustainable family businesses in Ghana, integrity in trade, and spiritual headship.',
    theme: 'Kingdom Wealth & Generational Legacy',
    theme_scripture: 'Deuteronomy 8:18',
    event_type: 'leadership',
    start_date: '2026-11-07',
    end_date: '2026-11-07',
    start_time: '07:30',
    end_time: '12:00',
    venue: 'GWCC Executive Conference Room & Annex',
    organizer: 'Men of Valour Fellowship',
    speaker: 'Bro. Samuel Kweku Appiah & Guest Banking Consultant',
    ministry_name: 'Men of Valour (Men Fellowship)',
    expected_attendance: 120,
    budget: 4800,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 55,
    banner_color: 'blue',
    attendees: [
      { id: 'att-13', name: 'Kwame Owusu Mensah', phone: '+233 24 456 1234', role: 'Co-Host', registered_at: '2026-09-21T09:00:00Z', checked_in: false },
      { id: 'att-14', name: 'Emmanuel Nana Boateng', phone: '+233 24 333 5566', role: 'Attendee', registered_at: '2026-09-21T11:00:00Z', checked_in: false },
    ],
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-007',
    title: '21-Day Annual Congregational Prayer & Fasting',
    description: 'Corporate spiritual consecration seeking God’s guidance for the church and families, breaking into new dimensions of spiritual authority and harvest.',
    theme: 'Revival, Restoration & Greater Exploits',
    theme_scripture: 'Daniel 9:3',
    event_type: 'fasting',
    start_date: '2026-11-09',
    end_date: '2026-11-29',
    start_time: '18:00',
    end_time: '20:00',
    venue: 'GWCC Main Sanctuary & Online Livestream',
    organizer: 'Pastoral Board & Prayer Network',
    speaker: 'Prophet Elisha K. Richard',
    ministry_name: 'Pastoral & Ministerial Council',
    expected_attendance: 380,
    budget: 3500,
    status: 'upcoming',
    requires_registration: false,
    registration_count: 0,
    banner_color: 'amber',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-008',
    title: 'GWCC Annual Carol Service & Festival of Nine Lessons',
    description: 'Joyous celebration of Christ’s nativity with glorious choral renditions by Voices of Glory, musical orchestra, children’s nativity pageant, and festive candlelight dinner.',
    theme: 'Unto Us A Savior Is Born',
    theme_scripture: 'Isaiah 9:6',
    event_type: 'banquet',
    start_date: '2026-12-20',
    end_date: '2026-12-20',
    start_time: '17:00',
    end_time: '21:00',
    venue: 'GWCC Main Sanctuary, Joma',
    organizer: 'Music & Creative Arts Ministry',
    speaker: 'Prophet Elisha K. Richard',
    ministry_name: 'Music & Creative Arts (Voices of Glory)',
    expected_attendance: 550,
    budget: 12000,
    status: 'draft',
    requires_registration: false,
    registration_count: 0,
    banner_color: 'emerald',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'evt-009',
    title: 'Watch Night Crossover Service 2026/2027',
    description: 'The monumental crossover night into the prophetic Year of Supernatural Fruitfulness. Thanksgiving, foot-washing, prophetic declaration, and fireworks ushering in 2027.',
    theme: 'Crossing Over into Supernatural Dominion',
    theme_scripture: 'Joshua 3:5',
    event_type: 'all_night',
    start_date: '2026-12-31',
    end_date: '2027-01-01',
    start_time: '20:30',
    end_time: '02:30',
    venue: 'GWCC Main Auditorium & Extended Grounds, Joma, Accra',
    organizer: 'Pastoral Board & Executive Committee',
    speaker: 'Prophet Elisha K. Richard',
    ministry_name: 'Pastoral & Ministerial Council',
    expected_attendance: 900,
    budget: 20000,
    status: 'draft',
    requires_registration: false,
    registration_count: 0,
    banner_color: 'rose',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
];

export const samplePastoralCare: PastoralCareRecord[] = [
  {
    id: 'pas-001',
    member_id: 'mem-001',
    member_name: 'Kwame Owusu Mensah',
    member_phone: '+233 24 456 1234',
    date: '2026-09-18',
    care_type: 'counseling',
    assigned_pastor: 'Pastor David Osei-Tutu',
    follow_up_date: '2026-10-02',
    status: 'in_progress',
    notes: 'Family counseling and prayer over daughter preparing for BECE examinations. Very positive spirit.',
    is_confidential: true,
    created_at: '2026-09-18T14:30:00Z',
  },
  {
    id: 'pas-002',
    member_id: 'mem-004',
    member_name: 'Esi Akua Darko',
    member_phone: '+233 24 999 4433',
    date: '2026-09-12',
    care_type: 'home_visit',
    assigned_pastor: 'Lady Pastor Mercy Agyemang',
    status: 'completed',
    notes: 'Pastoral home visitation after surgery recovery. She has regained full strength and returned to teaching.',
    is_confidential: false,
    created_at: '2026-09-12T16:00:00Z',
  },
];

export const samplePrayerRequests: PrayerRequest[] = [
  {
    id: 'pry-001',
    member_id: 'mem-006',
    requester_name: 'Priscilla Ama Adjei',
    requester_phone: '+233 54 888 1234',
    category: 'Academic & Licensure',
    request: 'Praying for exceptional memory retention and divine favor in upcoming Ghana Nursing and Midwifery Council exams.',
    date_submitted: '2026-09-19',
    assigned_leader: 'Evangelist Paulina Akoto',
    status: 'praying',
    is_confidential: false,
    created_at: '2026-09-19T08:00:00Z',
  },
  {
    id: 'pry-002',
    requester_name: 'Brother Prince Lamptey',
    requester_phone: '+233 24 991 2233',
    category: 'Healing',
    request: 'Healing of mother hospitalized at Korle Bu Teaching Hospital with high blood pressure.',
    date_submitted: '2026-09-17',
    assigned_leader: 'Pastor David Osei-Tutu',
    status: 'praying',
    is_confidential: true,
    created_at: '2026-09-17T11:30:00Z',
  },
  {
    id: 'pry-003',
    member_id: 'mem-003',
    requester_name: 'Kofi Badu Asante',
    requester_phone: '+233 55 123 9876',
    category: 'Employment & Career',
    request: 'Submitted proposal for international contract. Praying for approval.',
    date_submitted: '2026-08-25',
    assigned_leader: 'Prophet Elisha K. Richard',
    status: 'answered',
    testimony: 'Praise God! The contract was approved and signed on September 15th with double the expected rate!',
    is_confidential: false,
    created_at: '2026-08-25T10:00:00Z',
  },
];

export const sampleCommunications: CommunicationRecord[] = [
  {
    id: 'com-001',
    title: 'Sunday Service Reminder & Transportation Notice',
    channel: 'sms',
    recipient_type: 'all_members',
    recipient_count: 245,
    message: 'Shalom saints! Join us tomorrow at GWCC for our Prophetic Encounter (7:30am) & Celebration Service (10:00am). Church shuttle bus starts from Ablekuma curve at 7:00am. Be blessed!',
    sender_id: 'GWCC',
    status: 'sent',
    sent_at: '2026-09-19T18:00:00Z',
  },
  {
    id: 'com-002',
    title: 'First-Time Visitors Appreciation & Welcome',
    channel: 'whatsapp',
    recipient_type: 'visitors',
    recipient_count: 14,
    message: 'Greetings from Greater Works City Church, Joma! We were blessed to have you worship with us this Sunday. Prophet Elisha and the leadership welcome you into the family of believers. Have a glorious week!',
    sender_id: 'GWCC',
    status: 'sent',
    sent_at: '2026-09-21T09:30:00Z',
  },
];

export const sampleAuditLogs: AuditLog[] = [
  {
    id: 'aud-001',
    user_name: 'Akosua Frimpong',
    user_role: 'Finance Officer',
    action: 'RECORD_GIVING',
    module: 'Finance',
    record_id: 'giv-001',
    details: 'Recorded Tithe of GH₵ 1,450.00 from Kwame Owusu Mensah via MTN MoMo',
    timestamp: '2026-09-20T08:45:12Z',
  },
  {
    id: 'aud-002',
    user_name: 'Ebenezer Quaye',
    user_role: 'Attendance Officer',
    action: 'TAKE_ATTENDANCE',
    module: 'Attendance',
    record_id: 'att-001',
    details: 'Checked in 6 members for Sunday 2nd Service',
    timestamp: '2026-09-20T10:20:00Z',
  },
  {
    id: 'aud-003',
    user_name: 'Kofi Mensah-Bonsu',
    user_role: 'Super Admin',
    action: 'CREATE_MEMBER',
    module: 'Members',
    record_id: 'mem-008',
    details: 'Registered new member Dorothy Ansah (GWCC-000008)',
    timestamp: '2026-08-10T11:00:00Z',
  },
  {
    id: 'aud-004',
    user_name: 'Pastor David Osei-Tutu',
    user_role: 'Pastor',
    action: 'PASTORAL_CARE_ENTRY',
    module: 'Pastoral Care',
    record_id: 'pas-001',
    details: 'Recorded counseling session with Kwame Owusu Mensah',
    timestamp: '2026-09-18T14:30:22Z',
  },
];
